---
abstract: 'Math is HARD (faster)'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: Hand
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-Math-XS
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/acme-math-xs-pm/issues
  homepage: https://github.com/ingydotnet/acme-math-xs-pm
  repository: https://github.com/ingydotnet/acme-math-xs-pm.git
version: 0.0.6
